### PR TITLE
generate more precise gobra.yml

### PR DESCRIPTION
**Pull request by Dspil**
With this configuration the real `gobra.yml` is saved in the root directory and is called `metagobra.yml`.  `.github/workflows/gobra.yml` is automatically generated by transforming `metagobra.yml` using `ymlmaker.py`. There are two features:

When we want to verify a package in the yml but some functions need different arguments we can add a flag called `disect` with value 1 just like in `metagobra.yml` in line `205`. In the corresponding package we can add annotations to functions (and outline blocks) as follows:
- The annotation should be directly in the line above the 'func' keyword declaring the func.
- The annotation has the form `// $![<flags space seperated>]!$` with possible flags:
  - `disableMoreCompleteExhale`
  - isolate (an action will be made just for this function)
  - closure (put over closures so the dumb parser ignores then and doesn't ask gobra to verify the specific line)
  An example is at `dataplane.go` line `228`

If a flag is unrecognized a warning will be issued for safety.

All entries of the `metagobra.yml` file that do not have the `disect` flag will be left as they are.
The rest will be split into two groups:
- The first group will have the flag `disableMoreCompleteExhale`
-  The fourth will have none
In each group all methods needing the corresponding flags will be asked to be verified by specifying the line they are defined at (if a group is empty, no corresponding action is generated).

All actions are then split into different workflows so they can run in parallel.

### CODE REVIEW

**Comment by jcp19** [comment]
Does this mean that we need to run the script to generate the files every time we update the CI and re-upload them? I'm a bit afraid that this will clutter too much our commits (for example, this file has almost 1000 lines of CI configs that we would, potentially, need to have in every PR) and that it might be a bit too easy to forget to do. If this really makes things faster then the alternative of not having it, then I would accept having this but do we have a compelling case right now to merge given that it still times out?

**Comment by Dspil** [comment]
I think I can drop the whole thing to below one hour.

**Comment by Dspil** [comment]
Now setkey takes 1h14m and everything else takes less but it runs in parallel. The total time you have to wait is 1h14m and nothing is trusted

**Comment by jcp19** [comment]
I will close this for now. @Dspil feel free to reopen in the future if this ever becomes needed again or if you write a script to run as fast as possible locally (not urgent at all though)

**Pull request closed without merging**
