### PR TITLE
IO-Spec Update

### PR DESCRIPTION
**Pull request by mlimbeck**
This PR includes the updated IO specification to resolve the issue with valid interfaces for packets destined for the local AS.

### CODE REVIEW

**Comment by jcp19** [comment]
Can we merge this already in master instead of the IO spec?

**Review by jcp19 — COMMENTED** [review]
Are there any changes to `dp2_enter_guard` or `dp2_forward_ext_guard` which are marked in the diff?

**Comment by mlimbeck** [comment]
Yes, I would merge this directly into master.

**Comment by jcp19** [comment]
> Yes, I would merge this directly into master.

oops, my bad. this commit history confused me.

**Review by jcp19 — APPROVED** [review]

**Pull request merged**
